# Generated by Django 6.0.2 on 2026-03-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='promptrequest',
            name='task_type',
            field=models.CharField(choices=[('summarize', 'Summarize'), ('rewrite', 'Rewrite'), ('explain', 'Explain'), ('generate', 'Generate ideas'), ('analyze', 'Analyze text')], max_length=20),
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('response_text', models.TextField()),
                ('token_usage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='core.promptrequest')),
            ],
        ),
    ]
